[tasks.watch]
run_task = [
    { name = ["fmt", "clippy", "test"] }
]
watch = true

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.fmt]
command = "cargo"
args = ["fmt"]
